name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: nightly

      - uses: actions/checkout@v4

      - name: Build
        run: .\build.bat
